apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-doencas-agravos
  namespace: dashs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash-doencas-agravos
  template:
    metadata:
      labels:
        app: dash-doencas-agravos
    spec:
      serviceAccountName: dataiesb-dashs
      containers:
        - name: dash-doencas-agravos
          image: 248189947068.dkr.ecr.us-east-1.amazonaws.com/dash-doencas-agravos:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
          livenessProbe:
            httpGet:
              path: /doencas-agravos/
              port: 8050
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /doencas-agravos/
              port: 8050
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /doencas-agravos/
              port: 8050
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 60
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1536Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dash-doencas-agravos
  namespace: dashs
spec:
  selector:
    app: dash-doencas-agravos
  ports:
    - port: 8050
      targetPort: 8050
